language: java

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2b16b493c334ae816f2f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
